# Generated by Django 4.1.3 on 2022-11-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField()),
                ('IIN', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('middlename', models.CharField(max_length=25)),
                ('blood_group', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=10)),
                ('emergency_contact_number', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('widowed', 'widowed'), ('divorced', 'divorced'), ('separated', 'separated')], max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
