# Generated by Django 4.1.3 on 2022-11-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField()),
                ('IIN', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('middlename', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=25)),
                ('department_id', models.IntegerField()),
                ('specialization_id', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('highest', 'highest'), ('first', 'first'), ('average', 'average'), ('low', 'low')], max_length=25)),
                ('price_for_appointment', models.FloatField()),
                ('schedule_details', models.TextField(max_length=250)),
                ('education', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('homepage', models.CharField(max_length=50)),
            ],
        ),
    ]
