# Generated by Django 4.1.3 on 2022-11-27 06:46

from django.db import migrations, models
import django.db.models.deletion
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialization_alter_doctor_homepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[doctors.models.date_validation])),
                ('timeslot', models.CharField(choices=[('09:00 – 09:30', '09:00 – 09:30'), ('10:00 – 10:30', '10:00 – 10:30'), ('11:00 – 11:30', '11:00 – 11:30'), ('12:00 – 12:30', '12:00 – 12:30'), ('13:00 – 13:30', '13:00 – 13:30'), ('14:00 – 14:30', '14:00 – 14:30'), ('15:00 – 15:30', '15:00 – 15:30'), ('16:00 – 16:30', '16:00 – 16:30'), ('17:00 – 17:30', '17:00 – 17:30')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule_details',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='appointmentdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentdate',
            unique_together={('date', 'timeslot', 'user')},
        ),
    ]
