# Generated by Django 4.1.3 on 2022-11-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdate',
            old_name='user',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='request',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='appointmentdate',
            unique_together={('date', 'timeslot', 'doctor')},
        ),
    ]
